[dynasties]
names.prefixes = [
    "Stone",
    "Iron",
    "Gold",
    "Silver",
    "Black",
    "Red",
    "Deep",
    "High",
    "Storm",
    "Sun",
    "Frost",
    "Ember",
    "Wyvern",
    "Shadow",
    "Aero",
    "River",
]
names.suffixes = [
    "wood",
    "fall",
    "heart",
    "light",
    "rock",
    "thorn",
    "ion",
    "glade",
    "ford",
    "crest",
    "garde",
    "helm",
    "stone",
    "moor",
    "mere",
]

[provinces]
names.prefixes = [
    "Aethel",
    "Stone",
    "River",
    "High",
    "Sun",
    "Mist",
    "Ebon",
    "Azure",
    "Old",
    "Crim",
    "Gray",
    "Silver",
    "Vale",
    "Thorn",
    "North",
    "South",
]
names.suffixes = [
    "gard",
    "haven",
    "bend",
    "cross",
    "mere",
    "wood",
    "stead",
    "hold",
    "fall",
    "shire",
    "keep",
    "wall",
    "ford",
    "peak",
    "dale",
]

[characters.male]
names.prefixes = [
    "Al",
    "Bor",
    "Ka",
    "Ga",
    "Tor",
    "El",
    "Fa",
    "Ma",
    "Jo",
    "Ry",
    "Th",
    "Lo",
    "Va",
    "Cor",
    "Dar",
    "Si",
    "Zen",
    "Aethel",
    "Kael",
    "Morth",
    "Dre",
    "Ul",
    "Bran",
    "Fen",
    "Aelf",
]
names.infixes = [
    "ar",
    "in",
    "el",
    "en",
    "ric",
    "las",
    "lan",
    "gus",
    "or",
    "an",
    "tha",
    "bin",
    "dan",
    "dor",
    "eth",
    "im",
    "och",
    "us",
    "mir",
    "var",
    "wyn",
]
names.suffixes = [
    "ic",
    "us",
    "on",
    "ian",
    "us",
    "ek",
    "os",
    "as",
    "is",
    "yn",
    "ar",
    "d",
    "or",
    "um",
    "ax",
    "eon",
    "ok",
    "o",
    "gard",
]

[characters.female]
names.prefixes = [
    "El",
    "Ly",
    "Se",
    "An",
    "Is",
    "Bri",
    "Ro",
    "Ma",
    "Vi",
    "Ly",
    "Syl",
    "Ar",
    "Fre",
    "Li",
    "Ca",
    "Rhia",
    "Ael",
    "Myr",
    "Xy",
    "Gwen",
    "Eira",
    "Zia",
    "Kith",
    "Vex",
]
names.infixes = [
    "ar",
    "ra",
    "aph",
    "ya",
    "ol",
    "en",
    "ow",
    "ael",
    "ien",
    "san",
    "vie",
    "tem",
    "ya",
    "lia",
    "na",
    "wyn",
    "ora",
    "bel",
    "rin",
    "lani",
    "dith",
    "phina",
]
names.suffixes = [
    "a",
    "ine",
    "na",
    "de",
    "is",
    "nn",
    "ana",
    "dra",
    "s",
    "ia",
    "e",
    "tte",
    "elle",
    "ith",
    "wyn",
    "ra",
    "ia",
    "iel",
    "wen",
    "yn",
]

[terrain_types.modifiers]
wetlands = "Wetlands"
plains = "Plains"
hills = "Hills"
mountains = "Mountains"
water = "Water"

[biome_types.modifiers]
drylands = "Drylands"
grasslands = "Grasslands"
forest = "Forest"
jungle = "Jungle"
wasteland = "Wasteland"